apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildcard-backend
  namespace: wildcard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wildcard-backend
  template:
    metadata:
      labels:
        app: wildcard-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/jheroorehj/wildcard-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secret
