apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-ingress
  namespace: wildcard
spec:
  ingressClassName: traefik
  rules:
    - host: wildcard.example.com
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: wildcard-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wildcard-frontend
                port:
                  number: 80
